sudo: false
language: erlang
otp_release:
  - 20.0-rc1
env:
  - TRAVIS_NODE_VERSION="7"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - yarn
before_script:
  - wget http://s3.hex.pm/builds/elixir/master.zip
  - unzip -d elixir master.zip
  - export PATH=$(pwd)/elixir/bin:${PATH}
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
script:
  - yarn build
  - mix test
  - yarn test
  - yarn test-app
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbd8944d285c0696dc41
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
